# Generated by Django 4.2.4 on 2023-08-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização do Stand')),
                ('valor', models.FloatField(verbose_name='Preço do Stand')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=200, verbose_name='CNPJ')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('categoria_empresa', models.CharField(max_length=150, verbose_name='Categoria da Empresa')),
                ('quitado', models.BooleanField(verbose_name='Quitação')),
                ('stand', models.ManyToManyField(to='stand.stand')),
            ],
        ),
    ]
