# Generated by Django 4.2.4 on 2023-08-31 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=150, verbose_name='Categoria da Empresa')),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='categoria_empresa',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='stand',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stand.empresa', verbose_name='Nome da Empresa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='stand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stand.stand', verbose_name='Stand'),
            preserve_default=False,
        ),
    ]
